#include "HTML_String_Helper.h"

HTML_String_Helper::HTML_String_Helper() {
    this->htmlCodeHash = new QHash<QString, int>();
    this->Populate_HTML_Code_Hash();
}

HTML_String_Helper::~HTML_String_Helper() {
    delete this->htmlCodeHash;
    this->htmlCodeHash = nullptr;
}

QString HTML_String_Helper::Convert_From_HTML_Name(const QString &string) {
    QString fixedString;
    for (int i = 0; i < string.size(); ++i) {
        if (string.at(i).toLatin1() == '&') {
            int tmp = i;
            QString code;
            while (i < string.size()) {
                code += string.at(i);
                if (string.at(i).toLatin1() == ';') break;
                else ++i;
            }
            if (code.endsWith(";")) {
                fixedString += this->Get_String_From_Code(code);
            } else { //invalid code
                i = tmp;
                fixedString += string.at(i);
            }
        } else {
            fixedString += string.at(i);
        }
    }
    return fixedString;
}

QString HTML_String_Helper::Get_String_From_Code(const QString &code) {
    QHash<QString, int>::iterator iter = this->htmlCodeHash->find(code);
    if (iter == this->htmlCodeHash->end()) return code;
    switch (iter.value()) {
    default:        assert(false); return QString();
    case 32:        return " ";
    case 33:        return "!";
    case 34:        return "\"";
    case 35:        return "#";
    case 36:        return "$";
    case 37:        return "%";
    case 38:        return "&";
    case 39:        return "'";
    case 40:        return "(";
    case 41:        return ")";
    case 42:        return "*";
    case 43:        return "+";
    case 44:        return ",";
    case 45:        return "-";
    case 46:        return ".";
    case 47:        return "/";
    case 48:        return "0";
    case 49:        return "1";
    case 50:        return "2";
    case 51:        return "3";
    case 52:        return "4";
    case 53:        return "5";
    case 54:        return "6";
    case 55:        return "7";
    case 56:        return "8";
    case 57:        return "9";
    case 58:        return ":";
    case 59:        return ";";
    case 60:        return "<";
    case 61:        return "=";
    case 62:        return ">";
    case 63:        return "?";
    case 64:        return "@";
    case 65:        return "A";
    case 66:        return "B";
    case 67:        return "C";
    case 68:        return "D";
    case 69:        return "E";
    case 70:        return "F";
    case 71:        return "G";
    case 72:        return "H";
    case 73:        return "I";
    case 74:        return "J";
    case 75:        return "K";
    case 76:        return "L";
    case 77:        return "M";
    case 78:        return "N";
    case 79:        return "O";
    case 80:        return "P";
    case 81:        return "Q";
    case 82:        return "R";
    case 83:        return "S";
    case 84:        return "T";
    case 85:        return "U";
    case 86:        return "V";
    case 87:        return "W";
    case 88:        return "X";
    case 89:        return "Y";
    case 90:        return "Z";
    case 91:        return "[";
    case 92:        return "\\";
    case 93:        return "]";
    case 94:        return "^";
    case 95:        return "_";
    case 96:        return "`";
    case 97:        return "a";
    case 98:        return "b";
    case 99:        return "c";
    case 100:       return "d";
    case 101:       return "e";
    case 102:       return "f";
    case 103:       return "g";
    case 104:       return "h";
    case 105:       return "i";
    case 106:       return "j";
    case 107:       return "k";
    case 108:       return "l";
    case 109:       return "m";
    case 110:       return "n";
    case 111:       return "o";
    case 112:       return "p";
    case 113:       return "q";
    case 114:       return "r";
    case 115:       return "s";
    case 116:       return "t";
    case 117:       return "u";
    case 118:       return "v";
    case 119:       return "w";
    case 120:       return "x";
    case 121:       return "y";
    case 122:       return "z";
    case 123:       return "{";
    case 124:       return "|";
    case 125:       return "}";
    case 126:       return "~";
    case 160:       return " ";
    case 161:       return "¡";
    case 162:       return "¢";
    case 163:       return "£";
    case 164:       return "¤";
    case 165:       return "¥";
    case 166:       return "¦";
    case 167:       return "§";
    case 168:       return "¨";
    case 169:       return "©";
    case 170:       return "ª";
    case 171:       return "«";
    case 172:       return "¬";
    case 173:       return "-";
    case 174:       return "®";
    case 175:       return "¯";
    case 176:       return "°";
    case 177:       return "±";
    case 178:       return "²";
    case 179:       return "³";
    case 180:       return "´";
    case 181:       return "µ";
    case 182:       return "¶";
    case 183:       return "·";
    case 184:       return "¸";
    case 185:       return "¹";
    case 186:       return "º";
    case 187:       return "»";
    case 188:       return "¼";
    case 189:       return "½";
    case 190:       return "¾";
    case 191:       return "¿";
    case 192:       return "À";
    case 193:       return "Á";
    case 194:       return "Â";
    case 195:       return "Ã";
    case 196:       return "Ä";
    case 197:       return "Å";
    case 198:       return "Æ";
    case 199:       return "Ç";
    case 200:       return "È";
    case 201:       return "É";
    case 202:       return "Ê";
    case 203:       return "Ë";
    case 204:       return "Ì";
    case 205:       return "Í";
    case 206:       return "Î";
    case 207:       return "Ï";
    case 208:       return "Ð";
    case 209:       return "Ñ";
    case 210:       return "Ò";
    case 211:       return "Ó";
    case 212:       return "Ô";
    case 213:       return "Õ";
    case 214:       return "Ö";
    case 215:       return "×";
    case 216:       return "Ø";
    case 217:       return "Ù";
    case 218:       return "Ú";
    case 219:       return "Û";
    case 220:       return "Ü";
    case 221:       return "Ý";
    case 222:       return "Þ";
    case 223:       return "ß";
    case 224:       return "à";
    case 225:       return "á";
    case 226:       return "â";
    case 227:       return "ã";
    case 228:       return "ä";
    case 229:       return "å";
    case 230:       return "æ";
    case 231:       return "ç";
    case 232:       return "è";
    case 233:       return "é";
    case 234:       return "ê";
    case 235:       return "ë";
    case 236:       return "ì";
    case 237:       return "í";
    case 238:       return "î";
    case 239:       return "ï";
    case 240:       return "ð";
    case 241:       return "ñ";
    case 242:       return "ò";
    case 243:       return "ó";
    case 244:       return "ô";
    case 245:       return "õ";
    case 246:       return "ö";
    case 247:       return "÷";
    case 248:       return "ø";
    case 249:       return "ù";
    case 250:       return "ú";
    case 251:       return "û";
    case 252:       return "ü";
    case 253:       return "ý";
    case 254:       return "þ";
    case 255:       return "ÿ";
    case 338:       return "Œ";
    case 339:       return "œ";
    case 352:       return "Š";
    case 353:       return "š";
    case 376:       return "Ÿ";
    case 402:       return "ƒ";
    case 8211:      return "–";
    case 8212:      return "—";
    case 8216:      return "‘";
    case 8217:      return "’";
    case 8218:      return "‚";
    case 8220:      return "“";
    case 8221:      return "”";
    case 8222:      return "„";
    case 8224:      return "†";
    case 8225:      return "‡";
    case 8226:      return "•";
    case 8230:      return "…";
    case 8240:      return "‰";
    case 8364:      return "€";
    case 8482:      return "™";
    }
}

void HTML_String_Helper::Populate_HTML_Code_Hash() {
    this->htmlCodeHash->insert("&#32;", 32);
    this->htmlCodeHash->insert("&#33;", 33);
    this->htmlCodeHash->insert("&#34;", 34);
    this->htmlCodeHash->insert("&#35;", 35);
    this->htmlCodeHash->insert("&#36;", 36);
    this->htmlCodeHash->insert("&#37;", 37);
    this->htmlCodeHash->insert("&#38;", 38);
    this->htmlCodeHash->insert("&#39;", 39);
    this->htmlCodeHash->insert("&#40;", 40);
    this->htmlCodeHash->insert("&#41;", 41);
    this->htmlCodeHash->insert("&#42;", 42);
    this->htmlCodeHash->insert("&#43;", 43);
    this->htmlCodeHash->insert("&#44;", 44);
    this->htmlCodeHash->insert("&#45;", 45);
    this->htmlCodeHash->insert("&#46;", 46);
    this->htmlCodeHash->insert("&#47;", 47);
    this->htmlCodeHash->insert("&#48;", 48);
    this->htmlCodeHash->insert("&#49;", 49);
    this->htmlCodeHash->insert("&#50;", 50);
    this->htmlCodeHash->insert("&#51;", 51);
    this->htmlCodeHash->insert("&#52;", 52);
    this->htmlCodeHash->insert("&#53;", 53);
    this->htmlCodeHash->insert("&#54;", 54);
    this->htmlCodeHash->insert("&#55;", 55);
    this->htmlCodeHash->insert("&#56;", 56);
    this->htmlCodeHash->insert("&#57;", 57);
    this->htmlCodeHash->insert("&#58;", 58);
    this->htmlCodeHash->insert("&#59;", 59);
    this->htmlCodeHash->insert("&#60;", 60);
    this->htmlCodeHash->insert("&#61;", 61);
    this->htmlCodeHash->insert("&#62;", 62);
    this->htmlCodeHash->insert("&#63;", 63);
    this->htmlCodeHash->insert("&#64;", 64);
    this->htmlCodeHash->insert("&#65;", 65);
    this->htmlCodeHash->insert("&#66;", 66);
    this->htmlCodeHash->insert("&#67;", 67);
    this->htmlCodeHash->insert("&#68;", 68);
    this->htmlCodeHash->insert("&#69;", 69);
    this->htmlCodeHash->insert("&#70;", 70);
    this->htmlCodeHash->insert("&#71;", 71);
    this->htmlCodeHash->insert("&#72;", 72);
    this->htmlCodeHash->insert("&#73;", 73);
    this->htmlCodeHash->insert("&#74;", 74);
    this->htmlCodeHash->insert("&#75;", 75);
    this->htmlCodeHash->insert("&#76;", 76);
    this->htmlCodeHash->insert("&#77;", 77);
    this->htmlCodeHash->insert("&#78;", 78);
    this->htmlCodeHash->insert("&#79;", 79);
    this->htmlCodeHash->insert("&#80;", 80);
    this->htmlCodeHash->insert("&#81;", 81);
    this->htmlCodeHash->insert("&#82;", 82);
    this->htmlCodeHash->insert("&#83;", 83);
    this->htmlCodeHash->insert("&#84;", 84);
    this->htmlCodeHash->insert("&#85;", 85);
    this->htmlCodeHash->insert("&#86;", 86);
    this->htmlCodeHash->insert("&#87;", 87);
    this->htmlCodeHash->insert("&#88;", 88);
    this->htmlCodeHash->insert("&#89;", 89);
    this->htmlCodeHash->insert("&#90;", 90);
    this->htmlCodeHash->insert("&#91;", 91);
    this->htmlCodeHash->insert("&#92;", 92);
    this->htmlCodeHash->insert("&#93;", 93);
    this->htmlCodeHash->insert("&#94;", 94);
    this->htmlCodeHash->insert("&#95;", 95);
    this->htmlCodeHash->insert("&#96;", 96);
    this->htmlCodeHash->insert("&#97;", 97);
    this->htmlCodeHash->insert("&#98;", 98);
    this->htmlCodeHash->insert("&#99;", 99);
    this->htmlCodeHash->insert("&#100;", 100);
    this->htmlCodeHash->insert("&#101;", 101);
    this->htmlCodeHash->insert("&#102;", 102);
    this->htmlCodeHash->insert("&#103;", 103);
    this->htmlCodeHash->insert("&#104;", 104);
    this->htmlCodeHash->insert("&#105;", 105);
    this->htmlCodeHash->insert("&#106;", 106);
    this->htmlCodeHash->insert("&#107;", 107);
    this->htmlCodeHash->insert("&#108;", 108);
    this->htmlCodeHash->insert("&#109;", 109);
    this->htmlCodeHash->insert("&#110;", 110);
    this->htmlCodeHash->insert("&#111;", 111);
    this->htmlCodeHash->insert("&#112;", 112);
    this->htmlCodeHash->insert("&#113;", 113);
    this->htmlCodeHash->insert("&#114;", 114);
    this->htmlCodeHash->insert("&#115;", 115);
    this->htmlCodeHash->insert("&#116;", 116);
    this->htmlCodeHash->insert("&#117;", 117);
    this->htmlCodeHash->insert("&#118;", 118);
    this->htmlCodeHash->insert("&#119;", 119);
    this->htmlCodeHash->insert("&#120;", 120);
    this->htmlCodeHash->insert("&#121;", 121);
    this->htmlCodeHash->insert("&#122;", 122);
    this->htmlCodeHash->insert("&#123;", 123);
    this->htmlCodeHash->insert("&#124;", 124);
    this->htmlCodeHash->insert("&#125;", 125);
    this->htmlCodeHash->insert("&#126;", 126);
    this->htmlCodeHash->insert("&#160;", 160);
    this->htmlCodeHash->insert("&#161;", 161);
    this->htmlCodeHash->insert("&#162;", 162);
    this->htmlCodeHash->insert("&#163;", 163);
    this->htmlCodeHash->insert("&#164;", 164);
    this->htmlCodeHash->insert("&#165;", 165);
    this->htmlCodeHash->insert("&#166;", 166);
    this->htmlCodeHash->insert("&#167;", 167);
    this->htmlCodeHash->insert("&#168;", 168);
    this->htmlCodeHash->insert("&#169;", 169);
    this->htmlCodeHash->insert("&#170;", 170);
    this->htmlCodeHash->insert("&#171;", 171);
    this->htmlCodeHash->insert("&#172;", 172);
    this->htmlCodeHash->insert("&#173;", 173);
    this->htmlCodeHash->insert("&#174;", 174);
    this->htmlCodeHash->insert("&#175;", 175);
    this->htmlCodeHash->insert("&#176;", 176);
    this->htmlCodeHash->insert("&#177;", 177);
    this->htmlCodeHash->insert("&#178;", 178);
    this->htmlCodeHash->insert("&#179;", 179);
    this->htmlCodeHash->insert("&#180;", 180);
    this->htmlCodeHash->insert("&#181;", 181);
    this->htmlCodeHash->insert("&#182;", 182);
    this->htmlCodeHash->insert("&#183;", 183);
    this->htmlCodeHash->insert("&#184;", 184);
    this->htmlCodeHash->insert("&#185;", 185);
    this->htmlCodeHash->insert("&#186;", 186);
    this->htmlCodeHash->insert("&#187;", 187);
    this->htmlCodeHash->insert("&#188;", 188);
    this->htmlCodeHash->insert("&#189;", 189);
    this->htmlCodeHash->insert("&#190;", 190);
    this->htmlCodeHash->insert("&#191;", 191);
    this->htmlCodeHash->insert("&#192;", 192);
    this->htmlCodeHash->insert("&#193;", 193);
    this->htmlCodeHash->insert("&#194;", 194);
    this->htmlCodeHash->insert("&#195;", 195);
    this->htmlCodeHash->insert("&#196;", 196);
    this->htmlCodeHash->insert("&#197;", 197);
    this->htmlCodeHash->insert("&#198;", 198);
    this->htmlCodeHash->insert("&#199;", 199);
    this->htmlCodeHash->insert("&#200;", 200);
    this->htmlCodeHash->insert("&#201;", 201);
    this->htmlCodeHash->insert("&#202;", 202);
    this->htmlCodeHash->insert("&#203;", 203);
    this->htmlCodeHash->insert("&#204;", 204);
    this->htmlCodeHash->insert("&#205;", 205);
    this->htmlCodeHash->insert("&#206;", 206);
    this->htmlCodeHash->insert("&#207;", 207);
    this->htmlCodeHash->insert("&#208;", 208);
    this->htmlCodeHash->insert("&#209;", 209);
    this->htmlCodeHash->insert("&#210;", 210);
    this->htmlCodeHash->insert("&#211;", 211);
    this->htmlCodeHash->insert("&#212;", 212);
    this->htmlCodeHash->insert("&#213;", 213);
    this->htmlCodeHash->insert("&#214;", 214);
    this->htmlCodeHash->insert("&#215;", 215);
    this->htmlCodeHash->insert("&#216;", 216);
    this->htmlCodeHash->insert("&#217;", 217);
    this->htmlCodeHash->insert("&#218;", 218);
    this->htmlCodeHash->insert("&#219;", 219);
    this->htmlCodeHash->insert("&#220;", 220);
    this->htmlCodeHash->insert("&#221;", 221);
    this->htmlCodeHash->insert("&#222;", 222);
    this->htmlCodeHash->insert("&#223;", 223);
    this->htmlCodeHash->insert("&#224;", 224);
    this->htmlCodeHash->insert("&#225;", 225);
    this->htmlCodeHash->insert("&#226;", 226);
    this->htmlCodeHash->insert("&#227;", 227);
    this->htmlCodeHash->insert("&#228;", 228);
    this->htmlCodeHash->insert("&#229;", 229);
    this->htmlCodeHash->insert("&#230;", 230);
    this->htmlCodeHash->insert("&#231;", 231);
    this->htmlCodeHash->insert("&#232;", 232);
    this->htmlCodeHash->insert("&#233;", 233);
    this->htmlCodeHash->insert("&#234;", 234);
    this->htmlCodeHash->insert("&#235;", 235);
    this->htmlCodeHash->insert("&#236;", 236);
    this->htmlCodeHash->insert("&#237;", 237);
    this->htmlCodeHash->insert("&#238;", 238);
    this->htmlCodeHash->insert("&#239;", 239);
    this->htmlCodeHash->insert("&#240;", 240);
    this->htmlCodeHash->insert("&#241;", 241);
    this->htmlCodeHash->insert("&#242;", 242);
    this->htmlCodeHash->insert("&#243;", 243);
    this->htmlCodeHash->insert("&#244;", 244);
    this->htmlCodeHash->insert("&#245;", 245);
    this->htmlCodeHash->insert("&#246;", 246);
    this->htmlCodeHash->insert("&#247;", 247);
    this->htmlCodeHash->insert("&#248;", 248);
    this->htmlCodeHash->insert("&#249;", 249);
    this->htmlCodeHash->insert("&#250;", 250);
    this->htmlCodeHash->insert("&#251;", 251);
    this->htmlCodeHash->insert("&#252;", 252);
    this->htmlCodeHash->insert("&#253;", 253);
    this->htmlCodeHash->insert("&#254;", 254);
    this->htmlCodeHash->insert("&#255;", 255);
    this->htmlCodeHash->insert("&#338;", 338);
    this->htmlCodeHash->insert("&#339;", 339);
    this->htmlCodeHash->insert("&#352;", 352);
    this->htmlCodeHash->insert("&#353;", 353);
    this->htmlCodeHash->insert("&#376;", 376);
    this->htmlCodeHash->insert("&#402;", 402);
    this->htmlCodeHash->insert("&#8211;", 8211);
    this->htmlCodeHash->insert("&#8212;", 8212);
    this->htmlCodeHash->insert("&#8216;", 8216);
    this->htmlCodeHash->insert("&#8217;", 8217);
    this->htmlCodeHash->insert("&#8218;", 8218);
    this->htmlCodeHash->insert("&#8220;", 8220);
    this->htmlCodeHash->insert("&#8221;", 8221);
    this->htmlCodeHash->insert("&#8222;", 8222);
    this->htmlCodeHash->insert("&#8224;", 8224);
    this->htmlCodeHash->insert("&#8225;", 8225);
    this->htmlCodeHash->insert("&#8226;", 8226);
    this->htmlCodeHash->insert("&#8230;", 8230);
    this->htmlCodeHash->insert("&#8240;", 8240);
    this->htmlCodeHash->insert("&#8364;", 8364);
    this->htmlCodeHash->insert("&#8482;", 8482);
    this->htmlCodeHash->insert("&quot;", 34);
    this->htmlCodeHash->insert("&amp;", 38);
    this->htmlCodeHash->insert("&lt;", 60);
    this->htmlCodeHash->insert("&gt;", 62);
    this->htmlCodeHash->insert("&nbsp;", 160);
    this->htmlCodeHash->insert("&iexcl;", 161);
    this->htmlCodeHash->insert("&cent;", 162);
    this->htmlCodeHash->insert("&pound;", 163);
    this->htmlCodeHash->insert("&curren;", 164);
    this->htmlCodeHash->insert("&yen;", 165);
    this->htmlCodeHash->insert("&brvbar;", 166);
    this->htmlCodeHash->insert("&sect;", 167);
    this->htmlCodeHash->insert("&uml;", 168);
    this->htmlCodeHash->insert("&copy;", 169);
    this->htmlCodeHash->insert("&ordf;", 170);
    this->htmlCodeHash->insert("&laquo;", 171);
    this->htmlCodeHash->insert("&not;", 172);
    this->htmlCodeHash->insert("&shy;", 173);
    this->htmlCodeHash->insert("&reg;", 174);
    this->htmlCodeHash->insert("&macr;", 175);
    this->htmlCodeHash->insert("&deg;", 176);
    this->htmlCodeHash->insert("&plusmn;", 177);
    this->htmlCodeHash->insert("&sup2;", 178);
    this->htmlCodeHash->insert("&sup3;", 179);
    this->htmlCodeHash->insert("&acute;", 180);
    this->htmlCodeHash->insert("&micro;", 181);
    this->htmlCodeHash->insert("&para;", 182);
    this->htmlCodeHash->insert("&middot;", 183);
    this->htmlCodeHash->insert("&cedil;", 184);
    this->htmlCodeHash->insert("&sup1;", 185);
    this->htmlCodeHash->insert("&ordm;", 186);
    this->htmlCodeHash->insert("&raquo;", 187);
    this->htmlCodeHash->insert("&frac14;", 188);
    this->htmlCodeHash->insert("&frac12;", 189);
    this->htmlCodeHash->insert("&frac34;", 190);
    this->htmlCodeHash->insert("&iquest;", 191);
    this->htmlCodeHash->insert("&Agrave;", 192);
    this->htmlCodeHash->insert("&Aacute;", 193);
    this->htmlCodeHash->insert("&Acirc;", 194);
    this->htmlCodeHash->insert("&Atilde;", 195);
    this->htmlCodeHash->insert("&Auml;", 196);
    this->htmlCodeHash->insert("&Aring;", 197);
    this->htmlCodeHash->insert("&AElig;", 198);
    this->htmlCodeHash->insert("&Ccedil;", 199);
    this->htmlCodeHash->insert("&Egrave;", 200);
    this->htmlCodeHash->insert("&Eacute;", 201);
    this->htmlCodeHash->insert("&Ecirc;", 202);
    this->htmlCodeHash->insert("&Euml;", 203);
    this->htmlCodeHash->insert("&Igrave;", 204);
    this->htmlCodeHash->insert("&Iacute;", 205);
    this->htmlCodeHash->insert("&Icirc;", 206);
    this->htmlCodeHash->insert("&Iuml;", 207);
    this->htmlCodeHash->insert("&ETH;", 208);
    this->htmlCodeHash->insert("&Ntilde;", 209);
    this->htmlCodeHash->insert("&Ograve;", 210);
    this->htmlCodeHash->insert("&Oacute;", 211);
    this->htmlCodeHash->insert("&Ocirc;", 212);
    this->htmlCodeHash->insert("&Otilde;", 213);
    this->htmlCodeHash->insert("&Ouml;", 214);
    this->htmlCodeHash->insert("&times;", 215);
    this->htmlCodeHash->insert("&Oslash;", 216);
    this->htmlCodeHash->insert("&Ugrave;", 217);
    this->htmlCodeHash->insert("&Uacute;", 218);
    this->htmlCodeHash->insert("&Ucirc;", 219);
    this->htmlCodeHash->insert("&Uuml;", 220);
    this->htmlCodeHash->insert("&Yacute;", 221);
    this->htmlCodeHash->insert("&THORN;", 222);
    this->htmlCodeHash->insert("&szlig;", 223);
    this->htmlCodeHash->insert("&agrave;", 224);
    this->htmlCodeHash->insert("&aacute;", 225);
    this->htmlCodeHash->insert("&acirc;", 226);
    this->htmlCodeHash->insert("&atilde;", 227);
    this->htmlCodeHash->insert("&auml;", 228);
    this->htmlCodeHash->insert("&aring;", 229);
    this->htmlCodeHash->insert("&aelig;", 230);
    this->htmlCodeHash->insert("&ccedil;", 231);
    this->htmlCodeHash->insert("&egrave;", 232);
    this->htmlCodeHash->insert("&eacute;", 233);
    this->htmlCodeHash->insert("&ecirc;", 234);
    this->htmlCodeHash->insert("&euml;", 235);
    this->htmlCodeHash->insert("&igrave;", 236);
    this->htmlCodeHash->insert("&iacute;", 237);
    this->htmlCodeHash->insert("&icirc;", 238);
    this->htmlCodeHash->insert("&iuml;", 239);
    this->htmlCodeHash->insert("&eth;", 240);
    this->htmlCodeHash->insert("&ntilde;", 241);
    this->htmlCodeHash->insert("&ograve;", 242);
    this->htmlCodeHash->insert("&oacute;", 243);
    this->htmlCodeHash->insert("&ocirc;", 244);
    this->htmlCodeHash->insert("&otilde;", 245);
    this->htmlCodeHash->insert("&ouml;", 246);
    this->htmlCodeHash->insert("&divide;", 247);
    this->htmlCodeHash->insert("&oslash;", 248);
    this->htmlCodeHash->insert("&ugrave;", 249);
    this->htmlCodeHash->insert("&uacute;", 250);
    this->htmlCodeHash->insert("&ucirc;", 251);
    this->htmlCodeHash->insert("&uuml;", 252);
    this->htmlCodeHash->insert("&yacute;", 253);
    this->htmlCodeHash->insert("&thorn;", 254);
    this->htmlCodeHash->insert("&yuml;", 255);
    this->htmlCodeHash->insert("&euro;", 8364);

}
